spring:
  application:
    name: users
  profiles:
    active: local
  config:
    #import: optional:configserver:http://172.20.0.5:8085
    import: optional:configserver:http://localhost:8085
    #import: optional:configserver:http://host.docker.internal:8085
  #rabbitmq:
    #host: 172.20.0.3
    #host: localhost
    #host: host.docker.internal
    #port: 5672
    #username: guest
    #password: guest
  cloud:
    bus:
      enabled: false
      refresh:
        enabled: false

security.basic.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: ["*", "prometheus", "metrics", "health"]
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always
  security:
    enabled: false
  metrics:
    tags:
      application: app-micro-users

jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  expiration:
    ms: 60000