spring:
  application:
    name: users
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8085
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

security.basic.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: ["*", "prometheus", "metrics"]
  endpoint:
    beans:
      cache:
        time-to-live: 10s
  security:
    enabled: false
